/**
 * Claude Code types
 *
 * These types are designed to be compatible with Claude Agent SDK types
 * while remaining usable in the browser (no Node.js dependencies).
 */

/**
 * Permission mode for Claude session
 * Matches SDK's PermissionMode type
 *
 * - 'default': Normal mode with permission prompts
 * - 'acceptEdits': Accept file edits automatically
 * - 'plan': Plan mode (no code edits)
 * - 'bypassPermissions': Bypass permission prompts
 * - 'delegate': Delegate permission decisions
 * - 'dontAsk': Don't prompt for permissions, deny if not pre-approved
 */
export type PermissionMode =
  | 'default'
  | 'acceptEdits'
  | 'plan'
  | 'bypassPermissions'
  | 'delegate'
  | 'dontAsk';

/**
 * @deprecated Use PermissionMode instead
 */
export type ClaudePermissionMode = PermissionMode;

/**
 * Content block in a message (text, tool_use, or tool_result)
 * Simplified version compatible with SDK's content block structure
 */
export interface ContentBlock {
  type: 'text' | 'tool_use' | 'tool_result' | 'thinking';
  text?: string;
  id?: string;
  name?: string;
  input?: Record<string, unknown>;
  tool_use_id?: string;
  content?: string;
  is_error?: boolean;
}

/**
 * Base fields for SDK messages
 */
interface SDKMessageBase {
  uuid?: string;
  session_id: string;
}

/**
 * System init message from SDK
 */
export interface SystemInitMessage extends SDKMessageBase {
  type: 'system';
  subtype: 'init';
  tools: string[];
  model: string;
  permissionMode: PermissionMode;
  cwd: string;
  mcp_servers: { name: string; status: string }[];
  claude_code_version: string;
}

/**
 * Stream event (partial message) from SDK
 */
export interface StreamEventMessage extends SDKMessageBase {
  type: 'stream_event';
  event: {
    type: string;
    index?: number;
    delta?: {
      type: string;
      text?: string;
      partial_json?: string;
    };
    content_block?: {
      type: string;
      id?: string;
      name?: string;
      input?: Record<string, unknown>;
    };
  };
  parent_tool_use_id: string | null;
}

/**
 * Assistant message from SDK
 */
export interface AssistantMessage extends SDKMessageBase {
  type: 'assistant';
  message: {
    role: 'assistant';
    content: ContentBlock[];
    id?: string;
    model?: string;
    stop_reason?: string;
    usage?: {
      input_tokens?: number;
      output_tokens?: number;
    };
  };
  parent_tool_use_id: string | null;
}

/**
 * User message from SDK
 */
export interface UserMessage extends SDKMessageBase {
  type: 'user';
  message: {
    role: 'user';
    content: ContentBlock[];
  };
  parent_tool_use_id: string | null;
  tool_use_result?: unknown;
  isReplay?: boolean;
}

/**
 * Result message from SDK
 */
export interface ResultMessage extends SDKMessageBase {
  type: 'result';
  subtype: 'success' | 'error_during_execution' | 'error_max_turns' | 'error_max_budget_usd';
  result?: string;
  duration_ms: number;
  num_turns: number;
  total_cost_usd: number;
  is_error: boolean;
}

/**
 * Permission request message (synthetic, generated by backend for frontend compatibility)
 * This is not a native SDK type but is emitted by the backend when permission is needed.
 */
export interface ControlRequestMessage {
  type: 'control_request';
  request_id: string;
  request: {
    subtype: 'can_use_tool';
    tool_name: string;
    input: Record<string, unknown>;
    tool_use_id: string;
  };
}

/**
 * Union of message types used by the frontend
 * Includes SDK message types plus synthetic control_request for permissions
 */
export type ClaudeEvent =
  | SystemInitMessage
  | StreamEventMessage
  | AssistantMessage
  | UserMessage
  | ResultMessage
  | ControlRequestMessage;

/**
 * Processed message for UI display
 */
export interface ClaudeMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  thinking?: string;
  toolUse?: {
    id: string;
    name: string;
    input: Record<string, unknown>;
  }[];
  toolResults?: {
    toolUseId: string;
    content: string;
    isError?: boolean;
  }[];
  timestamp: string;
  isStreaming?: boolean;
}

/**
 * AskUserQuestion option
 */
export interface AskUserQuestionOption {
  label: string;
  description: string;
}

/**
 * AskUserQuestion question
 */
export interface AskUserQuestion {
  question: string;
  header: string;
  options: AskUserQuestionOption[];
  multiSelect: boolean;
}

/**
 * AskUserQuestion tool input
 */
export interface AskUserQuestionInput {
  questions: AskUserQuestion[];
}

/**
 * Pending permission request
 */
export interface ClaudePendingPermission {
  requestId: string;
  toolName: string;
  input: Record<string, unknown>;
  toolUseId: string;
  timestamp: string;
}

/**
 * Todo item from TodoWrite tool
 */
export interface TodoItem {
  content: string;
  status: 'pending' | 'in_progress' | 'completed';
  activeForm?: string;
}

/**
 * TodoWrite tool_use_result
 */
export interface TodoWriteResult {
  oldTodos: TodoItem[];
  newTodos: TodoItem[];
}
